################################################################
# Titre: otel-collector-config.yaml
# Description : Configuration du collecteur central Multi-Cloud
# Auteur: Ravindra JOB
# Source: https://github.com/ravindrajob/
# Update: 22/05/2026 [v2.1 | RJ]
################################################################

receivers:
  otlp:
    protocols:
      grpc:
      http:

  # 1. Receiver pour les flux AWS CloudWatch (via Kinesis)
  awscloudwatch:
    region: eu-west-3
    logs:
      groups: ["/lab-aws/central-audit-logs"]

  # 2. Receiver pour les flux Azure Monitor
  azuremonitor:
    subscription_id: ${AZURE_SUBSCRIPTION_ID}
    resource_group: "rg-lab-security"

  # 3. Receiver pour les flux GCP (Cloud Monitoring)
  googlecloudpubsub:
    project: ${GCP_PROJECT_ID}
    subscription: "projects/${GCP_PROJECT_ID}/subscriptions/lab-gcp-otel-sub"

processors:
  batch:
  resourcedetection:
    detectors: [env, azure, gcp, ec2]

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, azuremonitor, googlecloudpubsub]
      processors: [resourcedetection, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp, awscloudwatch, azuremonitor, googlecloudpubsub]
      processors: [resourcedetection, batch]
      exporters: [loki]
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [otlp]
